### ISSUE TITLE
manage ZOTERO folder

### ISSUE THREAD

**Issue by saraherm** [cbahlai/lampyrid#10]

**Comment by saraherm** [comment]
I'll work on this and post a link to the readme

**Comment by saraherm** [comment]
easiest way to upload information is through the browser plug-in. make sure you add notes on a summary or details that you have pulled from it to use in the paper.

**Comment by cbahlai** [comment]
Also! there are references in the paper that aren't in thee zotero library! needs to be synchronized.

**Comment by cbahlai** [comment]
This is looking pretty good now that I can use the word plugin and not the _tears_ overleaf approach. I think we're cool to close this issue- I will flag new issues if I can't find individual citations when editing the document
